// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Conversation is the predicate function for conversation builders.
type Conversation func(*sql.Selector)

// Prompt is the predicate function for prompt builders.
type Prompt func(*sql.Selector)
